

DELETE RANGERDEPT;

DELETE RANGER;

-- data 초기화.

INSERT INTO RANGER VALUES ( 'brown', '브라운');
INSERT INTO RANGER VALUES ( 'cony', '코니');
INSERT INTO RANGER VALUES ( 'sally', '샐리');
INSERT INTO RANGER VALUES ( 'moon', '문');
INSERT INTO RANGER VALUES ( 'james', '제임스');

INSERT INTO RANGERDEPT VALUES ('brown', '206');
INSERT INTO RANGERDEPT VALUES ('cony', '205');
INSERT INTO RANGERDEPT VALUES ('sally', '204');
INSERT INTO RANGERDEPT VALUES ('james', '203');
INSERT INTO RANGERDEPT VALUES ('moon', '202');

COMMIT;



